export const ROLES = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  CORPORATE: 'CORPORATE',
  WHOLESALE: 'WHOLESALE',
  STORE_MANAGER: 'STORE_MANAGER',
  SALESPERSON: 'SALESPERSON',
  MECHANIC: 'MECHANIC',
};

export const SCOPES = {
  ALL: '*',
  VIEW_DASHBOARD: 'view:dashboard',
  VIEW_INVENTORY: 'view:inventory',
  VIEW_RESTOCK: 'view:restock',
  VIEW_INSIGHTS: 'view:insights',
  VIEW_REPORTS: 'view:reports',
  VIEW_MECHANIC_STATS: 'view:mechanic_stats',
  VIEW_SALES_STATS: 'view:sales_stats',
  MANAGE_USERS: 'manage:users',
  IMPORT_DATA: 'import:data',
  CLEAR_DB: 'clear:db',
};

export const ROLE_SCOPES = {
  [ROLES.ADMINISTRATOR]: [SCOPES.ALL],
  [ROLES.CORPORATE]: [
    SCOPES.VIEW_DASHBOARD, 
    SCOPES.VIEW_INVENTORY, 
    SCOPES.VIEW_RESTOCK, 
    SCOPES.VIEW_INSIGHTS, 
    SCOPES.VIEW_REPORTS, 
    SCOPES.VIEW_MECHANIC_STATS, 
    SCOPES.VIEW_SALES_STATS
  ],
  [ROLES.WHOLESALE]: [SCOPES.VIEW_INVENTORY, SCOPES.VIEW_RESTOCK, SCOPES.VIEW_INSIGHTS],
  [ROLES.STORE_MANAGER]: [SCOPES.VIEW_DASHBOARD, SCOPES.VIEW_REPORTS, SCOPES.VIEW_INVENTORY],
  [ROLES.SALESPERSON]: [SCOPES.VIEW_SALES_STATS],
  [ROLES.MECHANIC]: [SCOPES.VIEW_MECHANIC_STATS],
};
